### ISSUE TITLE
Making Sheets For Menu Options In Account Details Page

### ISSUE THREAD

**Issue by macintAsh1984** [macintAsh1984/PiggyBank#18]
When a user clicks on the **Deposit**, **Withdraw**, or **Transfer** buttons, a SwiftUI Sheet should pop up (see Issue #14 to for an example with the Create Account option).

The **Deposit** and **Withdraw** options should display a Sheet with  Textfield with the amount the user wants to deposit and withdraw.

The Transfer button should display a Sheet with a list of accounts users can transfer money to.

This is just creating the UI so no backend implementation is required for this issue.

**Comment by smartha2003** [comment]
I DID IT!!
